name: Deployment Exercise 2
on: push
jobs:
  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Download code
  #      uses: actions/checkout@v3
  #    - name: Install dependencies
  #      run: npm ci
  #    - name: Lint Test
  #      run: npm run lint
  #Test:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Download code
  #      uses: actions/checkout@v3
  #    - name: Install dependecies
  #      run: npm ci
  #    - name: Test
  #      run: npm run test
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Build
        run: npm run build
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        echo: "Deployment done"
